### ISSUE TITLE
无法初始化，直接调用出现如下错误

### ISSUE THREAD

**Issue by Meorry** [Tamicer/FastDownloader#18]
兄弟不靠谱啊！！！！！
 java.lang.NullPointerException: Attempt to invoke interface method 'com.tamic.rx.fastdown.listener.IUIDownHandler com.tamic.rx.fastdown.listener.IDownloadListener.onHander()' on a null object reference
                                                                           at com.tamic.rx.fastdown.core.RxDLController.refreshDownloadingInfo(RxDLController.java:118)
                                                                           at com.tamic.rx.fastdown.core.RxDownloadManager$UIHandler.handleMessage(RxDownloadManager.java:681)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)

**Comment by Tamicer** [comment]
@Meorry https://github.com/Tamicer/FastDownloader/blob/master/simple/src/main/java/com/tamic/fastdownsimple/down/DownloadInit.java
